"""Added GeneratedVideo table

Revision ID: 1e0228a5b060
Revises: 5afc87181645
Create Date: 2020-01-20 12:23:38.146752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0228a5b060'
down_revision = '5afc87181645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_video',
    sa.Column('gvideoid', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('storagelocation', sa.String(length=500), nullable=True),
    sa.Column('createdTime', sa.DateTime(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('gvideoid')
    )
    op.create_index(op.f('ix_generated_video_createdTime'), 'generated_video', ['createdTime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_video_createdTime'), table_name='generated_video')
    op.drop_table('generated_video')
    # ### end Alembic commands ###
