"""Added VideoAnalyticsFile table

Revision ID: 31235b487259
Revises: dcdb6c12b4d2
Create Date: 2020-01-17 17:43:30.294588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31235b487259'
down_revision = 'dcdb6c12b4d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_analytics_file',
    sa.Column('analyticsfileid', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('storagelocation', sa.String(length=500), nullable=True),
    sa.Column('createdTime', sa.DateTime(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['uploaded_video.videoid'], ),
    sa.PrimaryKeyConstraint('analyticsfileid'),
    sa.UniqueConstraint('storagelocation')
    )
    op.create_index(op.f('ix_video_analytics_file_createdTime'), 'video_analytics_file', ['createdTime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_analytics_file_createdTime'), table_name='video_analytics_file')
    op.drop_table('video_analytics_file')
    # ### end Alembic commands ###
