"""Removed Unique Property From Tables

Revision ID: 5afc87181645
Revises: 31235b487259
Create Date: 2020-01-17 18:52:52.597500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5afc87181645'
down_revision = '31235b487259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uploaded_video_extension_key', 'uploaded_video', type_='unique')
    op.drop_constraint('uploaded_video_storagelocation_key', 'uploaded_video', type_='unique')
    op.drop_constraint('video_analytics_file_storagelocation_key', 'video_analytics_file', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('video_analytics_file_storagelocation_key', 'video_analytics_file', ['storagelocation'])
    op.create_unique_constraint('uploaded_video_storagelocation_key', 'uploaded_video', ['storagelocation'])
    op.create_unique_constraint('uploaded_video_extension_key', 'uploaded_video', ['extension'])
    # ### end Alembic commands ###
