"""added UploadedVideo table

Revision ID: dcdb6c12b4d2
Revises: 
Create Date: 2020-01-17 17:33:51.110143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcdb6c12b4d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_video',
    sa.Column('videoid', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('extension', sa.String(length=5), nullable=True),
    sa.Column('storagelocation', sa.String(length=500), nullable=True),
    sa.Column('uploadStartedTime', sa.DateTime(), nullable=True),
    sa.Column('uploadCompletedTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('videoid'),
    sa.UniqueConstraint('extension'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('storagelocation')
    )
    op.create_index(op.f('ix_uploaded_video_uploadCompletedTime'), 'uploaded_video', ['uploadCompletedTime'], unique=False)
    op.create_index(op.f('ix_uploaded_video_uploadStartedTime'), 'uploaded_video', ['uploadStartedTime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_video_uploadStartedTime'), table_name='uploaded_video')
    op.drop_index(op.f('ix_uploaded_video_uploadCompletedTime'), table_name='uploaded_video')
    op.drop_table('uploaded_video')
    # ### end Alembic commands ###
